# Conexión a sql server (AdventureWorks).
spring.datasource.url=jdbc:sqlserver://adventureworkspdp2.database.windows.net:1433;database=AdventureWorks;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=paul
spring.datasource.password=DW1210leo_?
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración de jpa/hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Interfaz web y entorno en desarrollo
server.port=8080
spring.thymeleaf.cache=false
