# Conexión a sql server (AdventureWorks).
spring.datasource.url=${CUSTOMECONNSTR_DBAZURECONNECTIONURL}
spring.datasource.username=${APP_USERNAME}
spring.datasource.password=${APP_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración de jpa/hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Interfaz web y entorno en desarrollo
server.port=8080
spring.thymeleaf.cache=false
